"""add show_in_gallery to products

Revision ID: 71d71444c0d9
Revises: b9d62d00878f
Create Date: 2026-08-07 14:04:36.491105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d71444c0d9'
down_revision = 'b9d62d00878f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_in_gallery', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('show_in_gallery')

    # ### end Alembic commands ###
